project_name: terraform-provider-signalcraft
before:
  hooks:
    - go mod tidy
builds:
  - id: provider
    main: ./main.go
    binary: terraform-provider-signalcraft
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
signs:
  - artifacts: checksum
release:
  draft: false
  prerelease: false
