-- Add Phase 1 integration types
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'AWS_CLOUDWATCH';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'PROMETHEUS';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'GRAFANA';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'GENERIC_WEBHOOK';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'JIRA';
